### ISSUE TITLE
logo proposal (since it is mentioned as missing on the homepage :-)

### ISSUE THREAD

**Issue by pythononwheels** [dsiroky/snakemq#10]
![snake_mq_logo_prop_1](https://cloud.githubusercontent.com/assets/1859655/10246929/8a813928-6915-11e5-962f-a6588d7eeb79.PNG)

Just an Idea.

**Comment by pythononwheels** [comment]
ok, two more views/variations
![snake_mq_logo_2](https://cloud.githubusercontent.com/assets/1859655/10256017/72505058-694e-11e5-91c8-96ef86b9568a.png)

**Comment by dsiroky** [comment]
Hi! This looks promising! Good idea with the "split-snake". However it will not look good in a smaller version, e.g. 50px height. Those dots will disappear. Maybe something more compact like:
![smq](https://cloud.githubusercontent.com/assets/1227818/10273755/a7e56382-6b35-11e5-824a-db522104510d.png)

**Comment by pythononwheels** [comment]
Yes, right. To be able to use the same logo in different sizes the dots are too tiny.

**Option 1: Bigger (but fewer) dots**

![snake_mq_logo_prop_50px_3]
(https://cloud.githubusercontent.com/assets/1859655/10279908/b394a95c-6b69-11e5-946e-ef64c92c7316.PNG)

**Option 2: No dots:**

*50px height*
![snake_mq_logo_prop_50px_4](https://cloud.githubusercontent.com/assets/1859655/10279995/4f27d04c-6b6a-11e5-96ed-34451b380139.PNG)

*100 px height:*

![snake_mq_logo_prop_100px_4](https://cloud.githubusercontent.com/assets/1859655/10280003/5897cec0-6b6a-11e5-95fe-31d254f635cd.PNG)

**Option 3: No dots, no Text:**

*33px height, 140 px width*

![snake_mq_logo_prop_140px_width_5](https://cloud.githubusercontent.com/assets/1859655/10280221/c4d48e42-6b6b-11e5-930e-0a155c8416c8.PNG)

*50px height* (212 px width)

![snake_mq_logo_prop_50px_5](https://cloud.githubusercontent.com/assets/1859655/10280217/bdfab3f8-6b6b-11e5-85e8-7adb7e46f07c.PNG)

*Does this look more like a message transfer ?*

![snake_mq_logo_prop_150px_width_6](https://cloud.githubusercontent.com/assets/1859655/10280265/29ba8898-6b6c-11e5-9f0c-3057a9d8a29a.PNG)

**Comment by dsiroky** [comment]
Me too, awesome! Could you please post an SVG version?

**Comment by pythononwheels** [comment]
great ! sure .

**Comment by pythononwheels** [comment]
via pull request ?
(->adding an image subfolder and 2 SVGs (on with text and one without) ???

upload svg in this issue is not supported ;(

**Comment by dsiroky** [comment]
Use http://filebin.net/ . SVG with text, thanks!

**Comment by pythononwheels** [comment]
You can find it here:  http://filebin.net/fmirvbfs21

Made with the great inkscape ;)
