### ISSUE TITLE
Windows deadlock race condition

### ISSUE THREAD

**Issue by arossert** [dsiroky/snakemq#20]
I have encountered a deadlock in race condition on Windows OS.

This is the scenario:

from `messaging.py` `_on_link_loop_pass()` is called and acquire the `self._lock` and calling `send_message_frame()` this drills down to `link.py` to the `send()` function, if an error occured and line `403` is calling `self.handle_close(sock)` it will call `on_disconnect` which will eventully call `_on_disconnect()` back in `messaging.py` and will try to aquire the `self._lock` again and we are in a deadlock.

I have solved this by replacing the `threading.Lock()` with `threading.RLock()` to allow the same thread acquiring the lock multiple times.

I'm not sure if this is the way to deal with this but it worked for me.
created a PR: https://github.com/dsiroky/snakemq/pull/19

**Comment by arossert** [comment]
@dsiroky thanks for merging this fix, is there any new release planned?

**Comment by dsiroky** [comment]
Thanks for the bugfix.

I don't plan a new release. It is a fully matured library with no further development. Just maintenance. I'll probably make a note in the readme that the github should be used as a main source.
